### ISSUE TITLE
Llama huggingface tokenizer missing tokens in config

### ISSUE THREAD

**Issue by anas-awadalla** [mlfoundations/open_flamingo#136]
When setting the tokens in `tokenizer_config.json` manually, it runs :)
```
{"bos_token": "<s>", "eos_token": "</s>", "model_max_length": 1000000000000000019884624838656, "tokenizer_class": "LlamaTokenizer", "unk_token": "<unk>"}
```

_Originally posted by @chs20 in https://github.com/mlfoundations/open_flamingo/issues/132#issuecomment-1489954011_

**Comment by Luodian** [comment]
hi I uploaded a compatible huggingface llama on https://huggingface.co/luodian/llama-7b-hf. 

This is updated from [decapoda-research/llama-7b-hf](https://huggingface.co/decapoda-research/Llama-7b-hf) (since the many pull requests are not merged yet in decapoda's repo, so I directly open a new repo here). It includes:

(1) The naming changes (LLaMA -> Llama) to best fit for transformers naming rule, in both LlamaForCausalLM and LlamaTokenizer. This works perfectly for transformers>=4.28.0.

(2) The model checkpoints are saved in 2 shards (instead of 33 shards in [decapoda-research/Llama-7b-hf](https://huggingface.co/decapoda-research/Llama-7b-hf)). Less shards would accelerate loading speed from disk.

you can just use `--lm_path=luodian/llama-7b-hf` and `--tokenizer_path=luodian/llama-7b-hf` to run the code.

**Comment by anas-awadalla** [comment]
Thanks for doing this! Works great.
