### ISSUE TITLE
About license

### ISSUE THREAD

**Issue by LangDaoAI** [mlfoundations/open_flamingo#141]
Hi Team,

I have seen a license created today, however, I have some questions as following:

1) If we fork the souce code and use our own data for fine-tuning, can we release models commercially?
2) If we use our own data for fine-tuning based on open flamingo released models, can we release models commercially?

Thanks!

**Comment by anas-awadalla** [comment]
The restriction on model use is due to Meta's rules prohibiting the commercial use of Llama models. Since our OpenFlamingo-9B model relies on a Llama backbone, you cannot use the model we provide (even if you fine-tune it) for any commercial purpose. However, you can use the codebase in any way you want. So you can train your own flamingo model that uses an LM other than Llama and use it commercially.

**Comment by LangDaoAI** [comment]
THANKS detailed reply very much!

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
